# This is a basic workflow to help you get started with Actions

name: "Update"

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow every hour
  schedule:
  - cron: "0 * * * *"
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2.4.0
    - name: "cd"
      run: cd $GITHUB_WORKSPACE
    - name: "Making update.sh executable, if not"
      run: chmod +x ./update.sh
    - name: "Updating"
      run: ./update.sh
