# This is a basic workflow to help you get started with Actions

name: "Update"

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow every hour
  schedule:
  - cron: "0 * * * *"
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2.4.0
    - name: "cd"
      run: cd $GITHUB_WORKSPACE
    - name: "Making update.sh executable, if not"
      run: chmod +x ./update.sh
    - name: "Updating"
      run: ./update.sh
    - name: getting time
      run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating the website"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master

