# This is a basic workflow to help you get started with Actions

name: "Update"

# Controls when the workflow will run
on:
  # Triggers the workflow every hour
  schedule:
  - cron: "0 * * * *"
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: "update"
      run: ./update.sh
